### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by gnimmelf** [morepath/more.chameleon#3]
Hi again,

I'm on a roll with morepath now (haha), and have decide to totally blacklist clientside logic in favour of good, old html. So in vein of my current zope-nostalgia, `more.chameleon`:

I tried this app-setup:

app.py

```
import morepath
from more.chameleon import ChameleonApp

class App(ChameleonApp):
    pass

@App.template_directory()
def get_template_directory():
    return 'templates'

@App.setting_section(section='chameleon')
def get_setting_section():
    return {'debug': True}
```

root.py

```
from app import App

@App.path(path='')
class Root(object):
    def __init__(self):
      self.name = 'Flemming Hansen'

@App.template_directory()
def get_template_directory():
    return 'templates'

@App.view(model=Root, template='root.pt')
def root_default(self, request):
    return {'name': self.name}
```

-But no matter how I move things around, I get this error message:

```
Traceback (most recent call last):
  File "app/run.py", line 20, in <module>
    dev()
  File "app/run.py", line 15, in dev
    config.commit()
  File "/home/gnimmelf/.venvs/morepath_env/lib/python3.4/site-packages/morepath-0.11.1-py3.4.egg/morepath/config.py", line 540, in commit
    configurable.execute()
  File "/home/gnimmelf/.venvs/morepath_env/lib/python3.4/site-packages/morepath-0.11.1-py3.4.egg/morepath/config.py", line 104, in execute
    actions.perform(self)
  File "/home/gnimmelf/.venvs/morepath_env/lib/python3.4/site-packages/morepath-0.11.1-py3.4.egg/morepath/config.py", line 175, in perform
    action.perform(configurable, obj)
  File "/home/gnimmelf/.venvs/morepath_env/lib/python3.4/site-packages/morepath-0.11.1-py3.4.egg/morepath/directive.py", line 566, in perform
    self.permission, self.internal)
  File "/home/gnimmelf/.venvs/morepath_env/lib/python3.4/site-packages/morepath-0.11.1-py3.4.egg/morepath/view.py", line 49, in register_view
    render = registry.get_template_render(template, render)
  File "/home/gnimmelf/.venvs/morepath_env/lib/python3.4/site-packages/morepath-0.11.1-py3.4.egg/morepath/template.py", line 58, in get_template_render
    "No template_loader configured for extension: %s" % extension)
morepath.error.ConfigError: No template_loader configured for extension: .pt
```

Am I just missing s.th really basic?

Thanks!

**Comment by gnimmelf** [comment]
Hmm, me thinks this is related to https://github.com/morepath/morepath/issues/345, as there are no complaints about the `template_loader` when I put everything in the same file...

**Comment by gnimmelf** [comment]
@href, @faassen I'm re-opening this issue, as I'm a bit confused as to where it actually belongs, and it seems I am spreading my problem out over a few issues...

[https://github.com/gnimmelf/morepath-blog]

**Comment by href** [comment]
I've checked your code and you are doing it just as you should. I tried it actually and it worked for me (root.pt renders correctly). Is it possible that you added more.chameleon to `setup.py` without running `python setup.py develop` or `python setup.py install` afterwards?

I suggest you just try that again. It worked for me :)

Also I found your issue with the werkzeug reloader and sent a pull request your way.

**Comment by gnimmelf** [comment]
1. Werkzeug and the pull request:
   A real night time bummer copy-paste, but now that I see it,  it's obvious.
2. Setup.py
   It did not occur to me that I had to run setup.py install to get the deps in setup.py, so I will do that again just to be sure. 

Thank you very much for the feedback =)

**Comment by href** [comment]
This seems to be a long-solved issue, so I'm closing it. Feel free to re-open if I'm wrong.
